//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFFactoryServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PdfRequestInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFServiceWebRole1")]
    public partial class PdfRequestInfo : object
    {
        
        private string BaseUrlField;
        
        private string FilenameField;
        
        private string HtmlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseUrl
        {
            get
            {
                return this.BaseUrlField;
            }
            set
            {
                this.BaseUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Html
        {
            get
            {
                return this.HtmlField;
            }
            set
            {
                this.HtmlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PDFFactoryServiceReference.IPdfFactory")]
    public interface IPdfFactory
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfFactory/GeneratePdf", ReplyAction="http://tempuri.org/IPdfFactory/GeneratePdfResponse")]
        System.Threading.Tasks.Task<string> GeneratePdfAsync(PDFFactoryServiceReference.PdfRequestInfo ddfRequestInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPdfFactory/CindiGeneratePdf", ReplyAction="http://tempuri.org/IPdfFactory/CindiGeneratePdfResponse")]
        System.Threading.Tasks.Task<string> CindiGeneratePdfAsync(PDFFactoryServiceReference.PdfRequestInfo ddfRequestInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IPdfFactoryChannel : PDFFactoryServiceReference.IPdfFactory, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class PdfFactoryClient : System.ServiceModel.ClientBase<PDFFactoryServiceReference.IPdfFactory>, PDFFactoryServiceReference.IPdfFactory
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PdfFactoryClient() : 
                base(PdfFactoryClient.GetDefaultBinding(), PdfFactoryClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IPdfFactory.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfFactoryClient(EndpointConfiguration endpointConfiguration) : 
                base(PdfFactoryClient.GetBindingForEndpoint(endpointConfiguration), PdfFactoryClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfFactoryClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PdfFactoryClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfFactoryClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PdfFactoryClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PdfFactoryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GeneratePdfAsync(PDFFactoryServiceReference.PdfRequestInfo ddfRequestInfo)
        {
            return base.Channel.GeneratePdfAsync(ddfRequestInfo);
        }
        
        public System.Threading.Tasks.Task<string> CindiGeneratePdfAsync(PDFFactoryServiceReference.PdfRequestInfo ddfRequestInfo)
        {
            return base.Channel.CindiGeneratePdfAsync(ddfRequestInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPdfFactory))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IPdfFactory))
            {
                return new System.ServiceModel.EndpointAddress("http://pdffactory.cloudapp.net/PdfFactory.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PdfFactoryClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IPdfFactory);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PdfFactoryClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IPdfFactory);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IPdfFactory,
        }
    }
}
